---
redis:
    # ultra lightweight redis
    image: redis:alpine
    ports:
        - 6379:6379
rabbitmq:
    image: rabbitmq:3-management
    ports:
        - 5672:5672
        # admin port
        - 15672:15672
