---
 - hosts: all
   tasks:
       - name: install pip
         yum: name=python-pip state=present
       - name: install docker
         yum: name=docker state=present
       - name: start and enable docker
         service: name=docker state=started enabled=yes
       - name: install docker-compose
         pip: name=docker-compose state=present
       - name: install redis cli tools
         yum: name=redis state=present
       - name: stop and disable redis
         service: name=redis state=stopped enabled=no
